version: "3.8"

services:

  # ---------------------------------------------------------------------------
  # POSTGRES (Banco de dados compartilhado)
  # ---------------------------------------------------------------------------
  postgres:
    image: postgres:15
    shm_size: 2gb
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    entrypoint: >
      bash -c "
      docker-entrypoint.sh postgres &
      until pg_isready -U airflow; do sleep 1; done;
      psql -U airflow -d airflow -c 'CREATE DATABASE data;' || true;
      wait"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ---------------------------------------------------------------------------
  # AIRFLOW - INIT (Prepara o banco utilizando os comandos nativos da imagem)
  # ---------------------------------------------------------------------------
  airflow-init:
    build: ./airflow
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      # Chave compartilhada para o airflow interagir entre os containers
      AIRFLOW__WEBSERVER__SECRET_KEY: "tcc_fia_labdata_engenharia_dados"
      AIRFLOW__CORE__FERNET_KEY: "7777777777777777777777777777777777777777777="
      # Variáveis nativas que criam automaticamente o usuário admin na inicialização do container
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      _AIRFLOW_WWW_USER_FIRSTNAME: Admin
      _AIRFLOW_WWW_USER_LASTNAME: User
      _AIRFLOW_WWW_USER_ROLE: Admin
      _AIRFLOW_WWW_USER_EMAIL: admin@example.com
    command: >
      bash -c "airflow db migrate &&
      airflow users create --username admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com --password admin &&
      airflow pools set pool_ingestao 2 'Pool exclusivo para limitar a ingestão a 2 task por vez' &&
      airflow pools set pool_sanitization 2 'Pool exclusivo para limitar a sanitizacao a 2 task por vez' &&
      airflow pools set pool_aggregation 2 'Pool exclusivo para limitar a agregacao a 2 task por vez'"
  # ---------------------------------------------------------------------------
  # AIRFLOW - WEBSERVER (Interface Gráfica na porta 8080)
  # ---------------------------------------------------------------------------
  airflow-webserver:
    build: ./airflow
    container_name: airflow-webserver
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      # Chave compartilhada para o airflow interagir entre os containers
      AIRFLOW__WEBSERVER__SECRET_KEY: "tcc_fia_labdata_engenharia_dados"
      AIRFLOW__CORE__FERNET_KEY: "7777777777777777777777777777777777777777777="
    command: webserver
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./DataPipeline:/opt/airflow/DataPipeline
      - ./Model:/opt/airflow/Model
      - ./airflow/data:/opt/airflow/data

  # ---------------------------------------------------------------------------
  # AIRFLOW - SCHEDULER (Executor e agendador das DAGs)
  # ---------------------------------------------------------------------------
  airflow-scheduler:
    build: ./airflow
    container_name: airflow-scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      # Conexão com postgres SQL do banco Data -> Vai criar um CONN ID automatico
      AIRFLOW_CONN_POSTGRES_DATA_DB: "postgresql://airflow:airflow@postgres:5432/data"
      # Chave compartilhada para o airflow interagir entre os containers
      AIRFLOW__WEBSERVER__SECRET_KEY: "tcc_fia_labdata_engenharia_dados"
      AIRFLOW__CORE__FERNET_KEY: "7777777777777777777777777777777777777777777="
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./DataPipeline:/opt/airflow/DataPipeline
      - ./Model:/opt/airflow/Model
      - ./airflow/data:/opt/airflow/data

  # ---------------------------------------------------------------------------
  # METABASE (Ferramenta de BI e Dashboards na porta 3000)
  # ---------------------------------------------------------------------------

  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter_fia
    ports:
      - "8888:8888"
    volumes:
      - ./DataPipeline:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    # Altere para a mesma rede que o seu Postgres e Airflow usam:
    depends_on:
      - postgres

volumes:
  pgdata:
