FROM python:3.12-slim

WORKDIR /app
COPY MLOps/app/api/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
COPY MLOps /app/MLOps
COPY Model/artifacts /app/Model/artifacts

ENV MODEL_PATH=/app/Model/artifacts/logistic_regression_abt.pkl
CMD ["uvicorn", "MLOps.app.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
