FROM python:3.12-slim

WORKDIR /app
COPY MLOps/app/frontend/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
COPY MLOps /app/MLOps

ENV CREDIT_API_URL=http://credit-api:8000
CMD ["streamlit", "run", "MLOps/app/frontend/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
